In [283]:
import chardet
import pandas as pd
import datetime

In [284]:
#with open('data/owner.csv', 'rb') as f:
#    result = chardet.detect(f.read())  # or readline if the file is large
#
#print(result)

In [285]:
# display full url for user_profile for instance
pd.set_option('display.max_colwidth', 1000)

In [286]:
owner = pd.read_csv("data/owner.csv",sep=';', encoding='ISO-8859-1')
prop = pd.read_csv("data/property.csv", sep=';', encoding='ISO-8859-1')

In [287]:
print("shape of owner is :" + str(owner.shape))
print("shape of prop is :" + str(prop.shape))

shape of owner is :(15127, 7)
shape of prop is :(18686, 14)

X   Créer une colone age
   Nettoyer languages
  X Calculer une colonne ancienneté
   Distribution des ages en fonction des hommes et femmes
   Scatter plot des last login
   Graph en barrer des created user
   Voir si gender correlé au last login

In [288]:
# vérification des années
#owner["Année de Birthdate"].unique()

In [289]:
# make a dictionary that maps the month name in french to a number
french_to_eng = {'janvier':'1','février':'2','mars': '3','avril': '4','mai':'5','juin':'6','juillet': '7','août': '8','septembre': '9','octobre':'10','novembre':'11','décembre':'12'}

# make new columsn for day month and year. For month, map the french name to month numbers
owner['day_sign_up'] = owner['Jour de Created At User'].apply(lambda x : x.split(' ')[0])
owner['month_sign_up'] = owner['Jour de Created At User'].apply(lambda x : x.split(' ')[1]).map(french_to_eng)
owner['year_sign_up'] = owner['Jour de Created At User'].apply(lambda x : x.split(' ')[2])

# make date time column from year, month and day.
owner['user_sign_up_date'] = pd.to_datetime(owner['year_sign_up']+'-'+owner['month_sign_up']+'-'+owner['day_sign_up'],format='%Y-%m-%d', errors='ignore')

owner = owner.drop(columns=['day_sign_up', 'month_sign_up', 'year_sign_up'])

In [290]:
owner['Jour de Last Login Date'].fillna(owner['Jour de Created At User'], inplace=True)

In [291]:
# make new columsn for day month and year. For month, map the french name to month numbers
owner['day_sign_in'] = owner['Jour de Last Login Date'].apply(lambda x : x.split(' ')[0])
owner['month_sign_in'] = owner['Jour de Last Login Date'].apply(lambda x : x.split(' ')[1]).map(french_to_eng)
owner['year_sign_in'] = owner['Jour de Last Login Date'].apply(lambda x : x.split(' ')[2])

# make date time column from year, month and day.
owner['user_sign_in_date'] = pd.to_datetime(owner['year_sign_in']+'-'+owner['month_sign_in']+'-'+owner['day_sign_in'],format='%Y-%m-%d', errors='ignore')

owner = owner.drop(columns=['day_sign_in', 'month_sign_in', 'year_sign_in'])

In [292]:
owner['user_sign_in_date'] = pd.to_datetime(owner['user_sign_in_date'])
owner['user_sign_up_date'] = pd.to_datetime(owner['user_sign_up_date'])

In [293]:
owner['today_date']= datetime.date.today()
owner['today_date']= pd.to_datetime(owner.today_date)

In [294]:
owner['seniority'] = owner.today_date - owner.user_sign_in_date
owner['days_since_last_login'] = owner.today_date - owner.user_sign_up_date

# quand owner['days_since_last_login'] vaut 0, on émet l'hypothèse que le compte est inactif

In [295]:
owner['year'] = datetime.date.today().year
owner['Année de Birthdate'] = owner['Année de Birthdate'].fillna(datetime.date.today().year)
owner['age'] = owner.year - owner['Année de Birthdate']
owner = owner.drop(columns=['Année de Birthdate', 'year', 'Jour de Created At User', 'Jour de Last Login Date'])

In [296]:
owner.head()

,Owner ID,Gender,Languages,Country,user_sign_up_date,user_sign_in_date,today_date,seniority,days_since_last_login,age
0,0a0e4-ad50-4b3a-81fd-a29ed0000,male,[],NaN,2018-05-12,2019-02-19,2019-06-14,115 days,398 days,0.0
1,0a1e1-1cfe-46d0-9069-e567bc9c3,female,[],NaN,2018-06-11,2018-06-26,2019-06-14,353 days,368 days,0.0
2,0a2b8-f8c2-4a2c-b6f8-d2f901abe,female,[],NaN,2018-04-17,2018-04-17,2019-06-14,423 days,423 days,0.0
3,0a2bd-8842-4067-b52e-0a8922be2,female,"[""en"", ""fr""]",NaN,2017-06-26,2017-07-17,2019-06-14,697 days,718 days,0.0
4,0a3ef-f75e-463c-b52b-fa39184d5,male,[],NaN,2018-03-09,2018-03-09,2019-06-14,462 days,462 days,0.0

In [310]:
owner[owner["Languages"].str.startswith('{')].head(10)

,Owner ID,Gender,Languages,Country,user_sign_up_date,user_sign_in_date,today_date,seniority,days_since_last_login,age
205,0d05d-4221-4833-87c8-6cffb9431,female,"{""1"": ""en"", ""2"": ""fr""}",NaN,2016-09-05,2018-06-27,2019-06-14,352 days,1012 days,0.0
733,2a0ae-3973-4758-b643-ba85bbce6,male,"{""0"": ""en"", ""2"": ""fr"", ""3"": ""pl""}",NaN,2017-05-23,2018-07-24,2019-06-14,325 days,752 days,0.0
912,2ca26-8e30-4a18-b398-9a5016f40,female,"{""0"": ""fr"", ""1"": ""de"", ""2"": ""en_GB""}",NaN,2017-10-04,2017-10-31,2019-06-14,591 days,618 days,0.0
1081,2fd26-c922-45c2-8049-9401d7edf,female,"{""1"": ""fr""}",NaN,2015-12-21,2019-05-15,2019-06-14,30 days,1271 days,79.0
1268,3cda7-ea43-4158-9a3e-74d0cf8b6,female,"{""0"": ""fr"", ""1"": ""en""}",NaN,2017-09-26,2018-10-23,2019-06-14,234 days,626 days,0.0
2287,6c0f3-2272-47b2-a84d-8c6c5fe6f,female,"{""1"": ""fr""}",NaN,2017-05-08,2018-06-18,2019-06-14,361 days,767 days,0.0
3079,8df17-b4c9-4bda-a843-2824e5003,female,"{""0"": ""fr"", ""2"": ""it""}",FR,2016-06-21,2019-05-31,2019-06-14,14 days,1088 days,63.0
3522,9f8e4-aaca-4420-9565-0a5d4f766,female,"{""1"": ""es"", ""2"": ""fr""}",NaN,2017-07-12,2017-07-18,2019-06-14,696 days,702 days,0.0
4255,31dbe-1cf0-4af0-bf48-ecfcca7b4,female,"{""1"": ""en"", ""2"": ""es"", ""3"": ""de""}",NaN,2017-08-26,2018-04-13,2019-06-14,427 days,657 days,0.0
4354,35d25-7990-4f12-838d-98ed9e04a,female,"{""1"": ""fr""}",NaN,2017-07-18,2018-03-20,2019-06-14,451 days,696 days,0.0

In [316]:
owner.loc[owner['Languages']].isin('{')

KeyError: 'None of [Index([\'[]\', \'[]\', \'[]\', \'["en", "fr"]\', \'[]\', \'["fr", "it"]\', \'[]\', \'[]\',\n       \'["fr", "en"]\', \'[]\',\n       ...\n       \'["fr"]\', \'["fr"]\', \'["en", "it"]\', \'[]\', \'[]\', \'["fr"]\', \'[]\', \'[]\',\n       \'[]\', \'["it"]\'],\n      dtype=\'object\', length=15127)] are in the [index]'

In [297]:
#Language design
#
owner[owner["Languages"] == '{"0": "fr", "1": "en"}']
owner[owner["Languages"].str.startswith('{')].head(10)
serie_lang = owner.Languages[owner["Languages"].str.startswith('{')]
serie_lang2 = serie_lang.str.strip("{}").str.split(":")